[package]
name = "nebulang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.12.3"
lazy_static = "1.4.0"
walkdir = "2.3.2"